//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugHelper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SorularModels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SorularModels()
        {
            this.ArtiOys = new HashSet<ArtiOys>();
            this.CevaplarModels = new HashSet<CevaplarModels>();
            this.EksiOys = new HashSet<EksiOys>();
            this.Etikets = new HashSet<Etikets>();
        }
    
        public int Id { get; set; }
        public string SoruIcerik { get; set; }
        public string SoruBaslik { get; set; }
        public System.DateTime SorulmaTarihi { get; set; }
        public string SoruSahibi { get; set; }
        public bool Onay { get; set; }
        public int TiklanmaSayisi { get; set; }
        public int CevapSayisi { get; set; }
        public int Deger { get; set; }
        public string KodlamaDili { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtiOys> ArtiOys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CevaplarModels> CevaplarModels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EksiOys> EksiOys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etikets> Etikets { get; set; }
    }
}
